// Auto-generated lure color images manifest
export const lureColorManifest = {
  "isca-artificial-danca-dagua": {
    "amareloneon": "iscas_cores/isca-artificial-danca-dagua/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-danca-dagua/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-danca-dagua/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-danca-dagua/Cha.png",
    "glow": "iscas_cores/isca-artificial-danca-dagua/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-danca-dagua/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-danca-dagua/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-danca-dagua/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-danca-dagua/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-danca-dagua/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-danca-dagua/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-danca-dagua/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-danca-dagua/Veu-da-noite.png"
  },
  "kit-isca-artificial-double-grub": {
    "amareloneon": "iscas_cores/kit-isca-artificial-double-grub/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-double-grub/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-double-grub/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-double-grub/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-double-grub/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-double-grub/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-double-grub/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-double-grub/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-double-grub/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-double-grub/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-double-grub/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-double-grub/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-double-grub/Veu-da-noite.png"
  },
  "kit-isca-artificial-easy-drift": {
    "amareloneon": "iscas_cores/kit-isca-artificial-easy-drift/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-easy-drift/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-easy-drift/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-easy-drift/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-easy-drift/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-easy-drift/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-easy-drift/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-easy-drift/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-easy-drift/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-easy-drift/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-easy-drift/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-easy-drift/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-easy-drift/Veu-da-noite.png"
  },
  "kit-isca-artificial-fatfish": {
    "amareloneon": "iscas_cores/kit-isca-artificial-fatfish/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-fatfish/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-fatfish/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-fatfish/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-fatfish/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-fatfish/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-fatfish/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-fatfish/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-fatfish/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-fatfish/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-fatfish/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-fatfish/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-fatfish/Veu-da-noite.png"
  },
  "kit-isca-artificial-fatworm": {
    "amareloneon": "iscas_cores/kit-isca-artificial-fatworm/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-fatworm/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-fatworm/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-fatworm/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-fatworm/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-fatworm/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-fatworm/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-fatworm/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-fatworm/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-fatworm/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-fatworm/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-fatworm/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-fatworm/Veu-da-noite.png"
  },
  "kit-isca-artificial-filotail": {
    "amareloneon": "iscas_cores/kit-isca-artificial-filotail/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-filotail/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-filotail/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-filotail/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-filotail/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-filotail/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-filotail/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-filotail/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-filotail/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-filotail/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-filotail/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-filotail/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-filotail/Veu-da-noite.png"
  },
  "kit-anteninha-2-unidades": {
    "preto": "iscas_cores/kit-anteninha-2-unidades/Preto.jpg",
    "marromclaro": "iscas_cores/kit-anteninha-2-unidades/Marrom-claro.jpg",
    "marromescuro": "iscas_cores/kit-anteninha-2-unidades/Marrom-escuro.jpg"
  },
  "isca-artificial-boom-paddle": {
    "amareloneon": "iscas_cores/isca-artificial-boom-paddle/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-boom-paddle/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-boom-paddle/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-boom-paddle/Cha.png",
    "glow": "iscas_cores/isca-artificial-boom-paddle/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-boom-paddle/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-boom-paddle/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-boom-paddle/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-boom-paddle/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-boom-paddle/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-boom-paddle/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-boom-paddle/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-boom-paddle/Veu-da-noite.png"
  },
  "isca-artificial-batelouca": {
    "amareloneon": "iscas_cores/isca-artificial-batelouca/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-batelouca/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-batelouca/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-batelouca/Cha.png",
    "glow": "iscas_cores/isca-artificial-batelouca/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-batelouca/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-batelouca/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-batelouca/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-batelouca/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-batelouca/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-batelouca/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-batelouca/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-batelouca/Veu-da-noite.png"
  },
  "isca-artificial-bait-boss": {
    "amareloneon": "iscas_cores/isca-artificial-bait-boss/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-bait-boss/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-bait-boss/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-bait-boss/Cha.png",
    "glow": "iscas_cores/isca-artificial-bait-boss/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-bait-boss/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-bait-boss/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-bait-boss/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-bait-boss/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-bait-boss/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-bait-boss/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-bait-boss/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-bait-boss/Veu-da-noite.png"
  },
  "kit-isca-artificial-claw-strike": {
    "amareloneon": "iscas_cores/kit-isca-artificial-claw-strike/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-claw-strike/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-claw-strike/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-claw-strike/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-claw-strike/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-claw-strike/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-claw-strike/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-claw-strike/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-claw-strike/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-claw-strike/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-claw-strike/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-claw-strike/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-claw-strike/Veu-da-noite.png"
  },
  "isca-artificial-camarao-chiclete": {
    "amareloneon": "iscas_cores/isca-artificial-camarao-chiclete/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-camarao-chiclete/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-camarao-chiclete/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-camarao-chiclete/Cha.png",
    "glow": "iscas_cores/isca-artificial-camarao-chiclete/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-camarao-chiclete/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-camarao-chiclete/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-camarao-chiclete/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-camarao-chiclete/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-camarao-chiclete/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-camarao-chiclete/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-camarao-chiclete/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-camarao-chiclete/Veu-da-noite.png"
  },
  "kit-isca-artificial-belly-fluke": {
    "amareloneon": "iscas_cores/kit-isca-artificial-belly-fluke/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-belly-fluke/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-belly-fluke/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-belly-fluke/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-belly-fluke/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-belly-fluke/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-belly-fluke/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-belly-fluke/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-belly-fluke/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-belly-fluke/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-belly-fluke/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-belly-fluke/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-belly-fluke/Veu-da-noite.png"
  },
  "isca-artificial-bubble-tube": {
    "amareloneon": "iscas_cores/isca-artificial-bubble-tube/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-bubble-tube/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-bubble-tube/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-bubble-tube/Cha.png",
    "glow": "iscas_cores/isca-artificial-bubble-tube/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-bubble-tube/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-bubble-tube/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-bubble-tube/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-bubble-tube/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-bubble-tube/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-bubble-tube/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-bubble-tube/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-bubble-tube/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajitwin": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajitwin/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajitwin/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajitwin/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajitwin/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajitwin/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajitwin/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajitwin/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajitwin/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajitwin/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajitwin/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajitwin/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajitwin/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajitwin/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajineedle-1": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajineedle-1/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajineedle-1/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajineedle-1/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajineedle-1/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajineedle-1/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajineedle-1/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajineedle-1/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajineedle-1/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajineedle-1/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajineedle-1/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajineedle-1/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajineedle-1/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajineedle-1/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajiring": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajiring/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajiring/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajiring/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajiring/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajiring/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajiring/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajiring/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajiring/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajiring/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajiring/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajiring/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajiring/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajiring/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajishirimp": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajishirimp/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajishirimp/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajishirimp/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajishirimp/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajishirimp/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajishirimp/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajishirimp/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajishirimp/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajishirimp/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajishirimp/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajishirimp/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajishirimp/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajishirimp/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajisho": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajisho/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajisho/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajisho/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajisho/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajisho/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajisho/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajisho/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajisho/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajisho/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajisho/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajisho/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajisho/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajisho/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajistingv": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajistingv/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajistingv/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajistingv/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajistingv/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajistingv/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajistingv/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajistingv/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajistingv/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajistingv/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajistingv/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajistingv/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajistingv/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajistingv/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajimushi": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajimushi/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajimushi/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajimushi/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajimushi/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajimushi/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajimushi/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajimushi/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajimushi/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajimushi/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajimushi/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajimushi/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajimushi/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajimushi/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajimizu": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajimizu/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajimizu/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajimizu/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajimizu/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajimizu/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajimizu/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajimizu/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajimizu/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajimizu/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajimizu/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajimizu/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajimizu/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajimizu/Veu-da-noite.png"
  },
  "isca-artificial-shad-padoru": {
    "amareloneon": "iscas_cores/isca-artificial-shad-padoru/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-shad-padoru/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-shad-padoru/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-shad-padoru/Cha.png",
    "glow": "iscas_cores/isca-artificial-shad-padoru/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-shad-padoru/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/isca-artificial-shad-padoru/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/isca-artificial-shad-padoru/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-shad-padoru/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-shad-padoru/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-shad-padoru/Veu-da-noite.png"
  },
  "isca-artificial-ajigrub": {
    "amareloneon": "iscas_cores/isca-artificial-ajigrub/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-ajigrub/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-ajigrub/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-ajigrub/Cha.png",
    "glow": "iscas_cores/isca-artificial-ajigrub/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-ajigrub/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/isca-artificial-ajigrub/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/isca-artificial-ajigrub/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-ajigrub/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-ajigrub/Vermelho-Holografico.png"
  },
  "kit-isca-artificial-aji-fukura": {
    "amareloneon": "iscas_cores/kit-isca-artificial-aji-fukura/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-aji-fukura/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-aji-fukura/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-aji-fukura/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-aji-fukura/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-aji-fukura/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-aji-fukura/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/kit-isca-artificial-aji-fukura/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-aji-fukura/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-aji-fukura/Vermelho-Holografico.png"
  },
  "kit-isca-artificial-ajiaero": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajiaero/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajiaero/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajiaero/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajiaero/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajiaero/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajiaero/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajiaero/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/kit-isca-artificial-ajiaero/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajiaero/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajiaero/Vermelho-Holografico.png"
  },
  "kit-isca-artificial-ajibeast": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajibeast/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajibeast/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajibeast/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajibeast/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajibeast/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajibeast/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajibeast/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/kit-isca-artificial-ajibeast/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajibeast/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajibeast/Vermelho-Holografico.png"
  },
  "kit-isca-artificial-ajiegg": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajiegg/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajiegg/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajiegg/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajiegg/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajiegg/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajiegg/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajiegg/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/kit-isca-artificial-ajiegg/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajiegg/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajiegg/Vermelho-Holografico.png"
  },
  "kit-isca-artificial-ajihane": {
    "amareloneon2": "iscas_cores/kit-isca-artificial-ajihane/amarelo-neon-2.png",
    "amareloneon": "iscas_cores/kit-isca-artificial-ajihane/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajihane/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajihane/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajihane/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajihane/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajihane/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajihane/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/kit-isca-artificial-ajihane/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajihane/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajihane/Vermelho-Holografico.png"
  },
  "kit-isca-artificial-ajikaze": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajikaze/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajikaze/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajikaze/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajikaze/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajikaze/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajikaze/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajikaze/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/kit-isca-artificial-ajikaze/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajikaze/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajikaze/Vermelho-Holografico.png"
  },
  "kit-isca-artificial-ajikoka": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajikoka/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajikoka/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajikoka/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajikoka/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajikoka/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajikoka/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajikoka/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/kit-isca-artificial-ajikoka/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajikoka/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajikoka/Vermelho-Holografico.png"
  },
  "kit-isca-artificial-wave-grub": {
    "amareloneon": "iscas_cores/kit-isca-artificial-wave-grub/amarelo-neon.png",
    "brancoperola2": "iscas_cores/kit-isca-artificial-wave-grub/Branco-perola-2.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-wave-grub/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-wave-grub/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-wave-grub/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-wave-grub/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-wave-grub/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-wave-grub/preto-brilhante.png",
    "roxoestrelnar": "iscas_cores/kit-isca-artificial-wave-grub/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-wave-grub/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-wave-grub/Vermelho-Holografico.png"
  }
};

export const getLureColorImage = (handle, colorName) => {
  if (!handle || !colorName || !lureColorManifest[handle]) return null;
  
  const normColor = colorName.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/g, '');
    
  const handleMap = lureColorManifest[handle];
  
  // Exact match
  if (handleMap[normColor]) {
    return `${import.meta.env.BASE_URL}${handleMap[normColor]}`;
  }
  
  // Partial / Fuzzy match
  for (const [key, path] of Object.entries(handleMap)) {
    if (key.includes(normColor) || normColor.includes(key)) {
      return `${import.meta.env.BASE_URL}${path}`;
    }
  }
  
  return null;
};
