// Auto-generated lure color images manifest
export const lureColorManifest = {
  "isca-artificial-serelepe": {
    "amareloneon": "iscas_cores/isca-artificial-serelepe/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-serelepe/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-serelepe/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-serelepe/Cha.png",
    "glow": "iscas_cores/isca-artificial-serelepe/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-serelepe/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-serelepe/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-serelepe/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-serelepe/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-serelepe/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-serelepe/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-serelepe/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-serelepe/Veu-da-noite.png"
  },
  "isca-artificial-shad-gaikotsu": {
    "amareloneon": "iscas_cores/isca-artificial-shad-gaikotsu/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-shad-gaikotsu/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-shad-gaikotsu/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-shad-gaikotsu/Cha.png",
    "glow": "iscas_cores/isca-artificial-shad-gaikotsu/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-shad-gaikotsu/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/isca-artificial-shad-gaikotsu/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/isca-artificial-shad-gaikotsu/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-shad-gaikotsu/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-shad-gaikotsu/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-shad-gaikotsu/Veu-da-noite.png",
    "pastel": "iscas_cores/isca-artificial-shad-gaikotsu/Pastel.png",
    "rapadura": "iscas_cores/isca-artificial-shad-gaikotsu/Rapadura.png",
  },
  "isca-artificial-ajimimizu": {
    "amareloneon": "iscas_cores/isca-artificial-ajimimizu/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-ajimimizu/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-ajimimizu/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-ajimimizu/Cha.png",
    "glow": "iscas_cores/isca-artificial-ajimimizu/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-ajimimizu/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-ajimimizu/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-ajimimizu/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-ajimimizu/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-ajimimizu/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-ajimimizu/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-ajimimizu/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-ajimimizu/Veu-da-noite.png"
  },
  "kit-isca-artificial-aji-nagare": {
    "amareloneon": "iscas_cores/kit-isca-artificial-aji-nagare/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-aji-nagare/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-aji-nagare/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-aji-nagare/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-aji-nagare/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-aji-nagare/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-aji-nagare/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-aji-nagare/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-aji-nagare/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-aji-nagare/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-aji-nagare/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-aji-nagare/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-aji-nagare/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajineedle": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajineedle/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajineedle/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajineedle/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajineedle/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajineedle/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajineedle/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajineedle/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajineedle/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajineedle/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajineedle/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajineedle/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajineedle/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajineedle/Veu-da-noite.png"
  },
  "isca-artificial-sapinho-costela": {
    "amareloneon": "iscas_cores/isca-artificial-sapinho-costela/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-sapinho-costela/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-sapinho-costela/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-sapinho-costela/Cha.png",
    "glow": "iscas_cores/isca-artificial-sapinho-costela/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-sapinho-costela/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-sapinho-costela/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-sapinho-costela/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-sapinho-costela/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-sapinho-costela/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-sapinho-costela/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-sapinho-costela/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-sapinho-costela/Veu-da-noite.png"
  },
  "isca-artificial-sapo-estica": {
    "amareloneon": "iscas_cores/isca-artificial-sapo-estica/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-sapo-estica/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-sapo-estica/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-sapo-estica/Cha.png",
    "glow": "iscas_cores/isca-artificial-sapo-estica/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-sapo-estica/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-sapo-estica/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-sapo-estica/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-sapo-estica/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-sapo-estica/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-sapo-estica/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-sapo-estica/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-sapo-estica/Veu-da-noite.png"
  },
  "kit-isca-artificial-snaketail": {
    "amareloneon": "iscas_cores/kit-isca-artificial-snaketail/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-snaketail/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-snaketail/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-snaketail/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-snaketail/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-snaketail/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-snaketail/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-snaketail/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-snaketail/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-snaketail/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-snaketail/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-snaketail/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-snaketail/Veu-da-noite.png"
  },
  "kit-soft-hattlin": {
    "amareloneon": "iscas_cores/kit-soft-hattlin/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-soft-hattlin/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-soft-hattlin/Capim-Rubi.png",
    "cha": "iscas_cores/kit-soft-hattlin/Cha.png",
    "glow": "iscas_cores/kit-soft-hattlin/Glow.png",
    "laranjaneon": "iscas_cores/kit-soft-hattlin/laranja-Neon.png",
    "pastel": "iscas_cores/kit-soft-hattlin/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-soft-hattlin/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-soft-hattlin/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-soft-hattlin/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-soft-hattlin/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-soft-hattlin/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-soft-hattlin/Veu-da-noite.png"
  },
  "isca-artificial-tatsumaki": {
    "amareloneon": "iscas_cores/isca-artificial-tatsumaki/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-tatsumaki/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-tatsumaki/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-tatsumaki/Cha.png",
    "glow": "iscas_cores/isca-artificial-tatsumaki/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-tatsumaki/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-tatsumaki/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-tatsumaki/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-tatsumaki/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-tatsumaki/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-tatsumaki/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-tatsumaki/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-tatsumaki/Veu-da-noite.png"
  },
  "kit-isca-artificial-tipworm": {
    "amareloneon": "iscas_cores/kit-isca-artificial-tipworm/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-tipworm/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-tipworm/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-tipworm/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-tipworm/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-tipworm/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-tipworm/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-tipworm/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-tipworm/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-tipworm/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-tipworm/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-tipworm/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-tipworm/Veu-da-noite.png"
  },
  "kit-isca-artificial-tornado-worm": {
    "amareloneon": "iscas_cores/kit-isca-artificial-tornado-worm/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-tornado-worm/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-tornado-worm/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-tornado-worm/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-tornado-worm/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-tornado-worm/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-tornado-worm/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-tornado-worm/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-tornado-worm/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-tornado-worm/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-tornado-worm/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-tornado-worm/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-tornado-worm/Veu-da-noite.png"
  },
  "kit-isca-artificial-vibraworm": {
    "amareloneon": "iscas_cores/kit-isca-artificial-vibraworm/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-vibraworm/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-vibraworm/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-vibraworm/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-vibraworm/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-vibraworm/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-vibraworm/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-vibraworm/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-vibraworm/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-vibraworm/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-vibraworm/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-vibraworm/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-vibraworm/Veu-da-noite.png"
  },
  "isca-artificial-viperbug": {
    "amareloneon": "iscas_cores/isca-artificial-viperbug/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-viperbug/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-viperbug/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-viperbug/Cha.png",
    "glow": "iscas_cores/isca-artificial-viperbug/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-viperbug/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-viperbug/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-viperbug/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-viperbug/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-viperbug/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-viperbug/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-viperbug/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-viperbug/Veu-da-noite.png"
  },
  "isca-artificial-linguado": {
    "amareloneon": "iscas_cores/isca-artificial-linguado/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-linguado/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-linguado/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-linguado/Cha.png",
    "glow": "iscas_cores/isca-artificial-linguado/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-linguado/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-linguado/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-linguado/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-linguado/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-linguado/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-linguado/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-linguado/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-linguado/Veu-da-noite.png"
  },
  "kit-isca-artificial-mini-paddle": {
    "amareloneon": "iscas_cores/kit-isca-artificial-mini-paddle/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-mini-paddle/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-mini-paddle/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-mini-paddle/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-mini-paddle/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-mini-paddle/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-mini-paddle/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-mini-paddle/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-mini-paddle/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-mini-paddle/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-mini-paddle/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-mini-paddle/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-mini-paddle/Veu-da-noite.png"
  },
  "kit-isca-artificial-morceguinho": {
    "amareloneon": "iscas_cores/kit-isca-artificial-morceguinho/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-morceguinho/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-morceguinho/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-morceguinho/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-morceguinho/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-morceguinho/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-morceguinho/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-morceguinho/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-morceguinho/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-morceguinho/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-morceguinho/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-morceguinho/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-morceguinho/Veu-da-noite.png"
  },
  "kit-isca-artificial-mustache-grub": {
    "amareloneon": "iscas_cores/kit-isca-artificial-mustache-grub/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-mustache-grub/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-mustache-grub/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-mustache-grub/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-mustache-grub/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-mustache-grub/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-mustache-grub/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-mustache-grub/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-mustache-grub/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-mustache-grub/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-mustache-grub/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-mustache-grub/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-mustache-grub/Veu-da-noite.png"
  },
  "kit-isca-artificial-pepino-do-mar": {
    "amareloneon": "iscas_cores/kit-isca-artificial-pepino-do-mar/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-pepino-do-mar/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-pepino-do-mar/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-pepino-do-mar/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-pepino-do-mar/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-pepino-do-mar/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-pepino-do-mar/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-pepino-do-mar/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-pepino-do-mar/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-pepino-do-mar/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-pepino-do-mar/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-pepino-do-mar/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-pepino-do-mar/Veu-da-noite.png"
  },
  "isca-artificial-pitu": {
    "amareloneon": "iscas_cores/isca-artificial-pitu/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-pitu/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-pitu/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-pitu/Cha.png",
    "glow": "iscas_cores/isca-artificial-pitu/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-pitu/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-pitu/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-pitu/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-pitu/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-pitu/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-pitu/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-pitu/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-pitu/Veu-da-noite.png"
  },
  "kit-isca-artificial-lagartail": {
    "amareloneon": "iscas_cores/kit-isca-artificial-lagartail/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-lagartail/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-lagartail/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-lagartail/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-lagartail/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-lagartail/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-lagartail/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-lagartail/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-lagartail/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-lagartail/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-lagartail/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-lagartail/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-lagartail/Veu-da-noite.png"
  },
  "kit-isca-artificial-lagartixa": {
    "amareloneon": "iscas_cores/kit-isca-artificial-lagartixa/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-lagartixa/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-lagartixa/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-lagartixa/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-lagartixa/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-lagartixa/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-lagartixa/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-lagartixa/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-lagartixa/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-lagartixa/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-lagartixa/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-lagartixa/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-lagartixa/Veu-da-noite.png"
  },
  "kit-isca-artificial-lagostim": {
    "amareloneon": "iscas_cores/kit-isca-artificial-lagostim/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-lagostim/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-lagostim/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-lagostim/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-lagostim/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-lagostim/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-lagostim/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-lagostim/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-lagostim/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-lagostim/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-lagostim/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-lagostim/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-lagostim/Veu-da-noite.png"
  },
  "kit-isca-artificial-legfrog": {
    "amareloneon": "iscas_cores/kit-isca-artificial-legfrog/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-legfrog/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-legfrog/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-legfrog/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-legfrog/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-legfrog/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-legfrog/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-legfrog/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-legfrog/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-legfrog/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-legfrog/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-legfrog/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-legfrog/Veu-da-noite.png"
  },
  "kit-isca-artificial-lesma": {
    "amareloneon": "iscas_cores/kit-isca-artificial-lesma/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-lesma/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-lesma/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-lesma/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-lesma/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-lesma/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-lesma/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-lesma/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-lesma/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-lesma/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-lesma/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-lesma/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-lesma/Veu-da-noite.png"
  },
  "kit-isca-artificial-lighthane": {
    "amareloneon": "iscas_cores/kit-isca-artificial-lighthane/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-lighthane/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-lighthane/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-lighthane/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-lighthane/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-lighthane/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-lighthane/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-lighthane/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-lighthane/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-lighthane/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-lighthane/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-lighthane/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-lighthane/Veu-da-noite.png"
  },
  "isca-artificial-grub": {
    "amareloneon": "iscas_cores/isca-artificial-grub/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-grub/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-grub/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-grub/Cha.png",
    "glow": "iscas_cores/isca-artificial-grub/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-grub/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-grub/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-grub/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-grub/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-grub/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-grub/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-grub/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-grub/Veu-da-noite.png"
  },
  "kit-isca-artificial-lacraworm-copia": {
    "amareloneon": "iscas_cores/kit-isca-artificial-lacraworm-copia/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-lacraworm-copia/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-lacraworm-copia/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-lacraworm-copia/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-lacraworm-copia/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-lacraworm-copia/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-lacraworm-copia/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-lacraworm-copia/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-lacraworm-copia/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-lacraworm-copia/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-lacraworm-copia/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-lacraworm-copia/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-lacraworm-copia/Veu-da-noite.png"
  },
  "kit-isca-artificial-folha": {
    "amareloneon": "iscas_cores/kit-isca-artificial-folha/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-folha/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-folha/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-folha/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-folha/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-folha/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-folha/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-folha/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-folha/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-folha/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-folha/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-folha/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-folha/Veu-da-noite.png"
  },
  "kit-isca-artificial-garra-brava": {
    "amareloneon": "iscas_cores/kit-isca-artificial-garra-brava/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-garra-brava/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-garra-brava/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-garra-brava/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-garra-brava/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-garra-brava/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-garra-brava/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-garra-brava/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-garra-brava/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-garra-brava/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-garra-brava/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-garra-brava/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-garra-brava/Veu-da-noite.png"
  },
  "kit-isca-artificial-gfluke": {
    "amareloneon": "iscas_cores/kit-isca-artificial-gfluke/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-gfluke/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-gfluke/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-gfluke/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-gfluke/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-gfluke/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-gfluke/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-gfluke/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-gfluke/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-gfluke/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-gfluke/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-gfluke/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-gfluke/Veu-da-noite.png"
  },
  "kit-isca-artificial-grilo": {
    "amareloneon": "iscas_cores/kit-isca-artificial-grilo/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-grilo/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-grilo/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-grilo/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-grilo/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-grilo/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-grilo/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-grilo/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-grilo/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-grilo/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-grilo/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-grilo/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-grilo/Veu-da-noite.png"
  },
  "isca-artificial-danca-dagua": {
    "amareloneon": "iscas_cores/isca-artificial-danca-dagua/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-danca-dagua/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-danca-dagua/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-danca-dagua/Cha.png",
    "glow": "iscas_cores/isca-artificial-danca-dagua/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-danca-dagua/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-danca-dagua/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-danca-dagua/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-danca-dagua/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-danca-dagua/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-danca-dagua/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-danca-dagua/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-danca-dagua/Veu-da-noite.png"
  },
  "kit-isca-artificial-double-grub": {
    "amareloneon": "iscas_cores/kit-isca-artificial-double-grub/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-double-grub/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-double-grub/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-double-grub/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-double-grub/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-double-grub/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-double-grub/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-double-grub/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-double-grub/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-double-grub/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-double-grub/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-double-grub/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-double-grub/Veu-da-noite.png"
  },
  "kit-isca-artificial-easy-drift": {
    "amareloneon": "iscas_cores/kit-isca-artificial-easy-drift/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-easy-drift/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-easy-drift/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-easy-drift/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-easy-drift/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-easy-drift/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-easy-drift/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-easy-drift/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-easy-drift/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-easy-drift/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-easy-drift/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-easy-drift/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-easy-drift/Veu-da-noite.png"
  },
  "kit-isca-artificial-fatfish": {
    "amareloneon": "iscas_cores/kit-isca-artificial-fatfish/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-fatfish/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-fatfish/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-fatfish/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-fatfish/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-fatfish/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-fatfish/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-fatfish/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-fatfish/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-fatfish/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-fatfish/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-fatfish/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-fatfish/Veu-da-noite.png"
  },
  "kit-isca-artificial-fatworm": {
    "amareloneon": "iscas_cores/kit-isca-artificial-fatworm/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-fatworm/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-fatworm/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-fatworm/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-fatworm/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-fatworm/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-fatworm/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-fatworm/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-fatworm/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-fatworm/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-fatworm/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-fatworm/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-fatworm/Veu-da-noite.png"
  },
  "kit-isca-artificial-filotail": {
    "amareloneon": "iscas_cores/kit-isca-artificial-filotail/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-filotail/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-filotail/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-filotail/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-filotail/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-filotail/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-filotail/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-filotail/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-filotail/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-filotail/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-filotail/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-filotail/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-filotail/Veu-da-noite.png"
  },
  "kit-anteninha-2-unidades": {
    "preto": "iscas_cores/kit-anteninha-2-unidades/Preto.jpg",
    "marromclaro": "iscas_cores/kit-anteninha-2-unidades/Marrom-claro.jpg",
    "marromescuro": "iscas_cores/kit-anteninha-2-unidades/Marrom-escuro.jpg"
  },
  "isca-artificial-boom-paddle": {
    "amareloneon": "iscas_cores/isca-artificial-boom-paddle/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-boom-paddle/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-boom-paddle/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-boom-paddle/Cha.png",
    "glow": "iscas_cores/isca-artificial-boom-paddle/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-boom-paddle/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-boom-paddle/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-boom-paddle/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-boom-paddle/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-boom-paddle/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-boom-paddle/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-boom-paddle/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-boom-paddle/Veu-da-noite.png"
  },
  "isca-artificial-batelouca": {
    "amareloneon": "iscas_cores/isca-artificial-batelouca/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-batelouca/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-batelouca/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-batelouca/Cha.png",
    "glow": "iscas_cores/isca-artificial-batelouca/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-batelouca/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-batelouca/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-batelouca/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-batelouca/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-batelouca/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-batelouca/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-batelouca/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-batelouca/Veu-da-noite.png"
  },
  "isca-artificial-bait-boss": {
    "amareloneon": "iscas_cores/isca-artificial-bait-boss/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-bait-boss/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-bait-boss/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-bait-boss/Cha.png",
    "glow": "iscas_cores/isca-artificial-bait-boss/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-bait-boss/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-bait-boss/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-bait-boss/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-bait-boss/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-bait-boss/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-bait-boss/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-bait-boss/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-bait-boss/Veu-da-noite.png"
  },
  "kit-isca-artificial-claw-strike": {
    "amareloneon": "iscas_cores/kit-isca-artificial-claw-strike/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-claw-strike/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-claw-strike/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-claw-strike/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-claw-strike/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-claw-strike/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-claw-strike/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-claw-strike/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-claw-strike/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-claw-strike/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-claw-strike/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-claw-strike/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-claw-strike/Veu-da-noite.png"
  },
  "isca-artificial-camarao-chiclete": {
    "amareloneon": "iscas_cores/isca-artificial-camarao-chiclete/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-camarao-chiclete/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-camarao-chiclete/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-camarao-chiclete/Cha.png",
    "glow": "iscas_cores/isca-artificial-camarao-chiclete/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-camarao-chiclete/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-camarao-chiclete/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-camarao-chiclete/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-camarao-chiclete/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-camarao-chiclete/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-camarao-chiclete/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-camarao-chiclete/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-camarao-chiclete/Veu-da-noite.png"
  },
  "kit-isca-artificial-belly-fluke": {
    "amareloneon": "iscas_cores/kit-isca-artificial-belly-fluke/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-belly-fluke/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-belly-fluke/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-belly-fluke/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-belly-fluke/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-belly-fluke/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-belly-fluke/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-belly-fluke/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-belly-fluke/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-belly-fluke/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-belly-fluke/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-belly-fluke/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-belly-fluke/Veu-da-noite.png"
  },
  "isca-artificial-bubble-tube": {
    "amareloneon": "iscas_cores/isca-artificial-bubble-tube/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-bubble-tube/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-bubble-tube/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-bubble-tube/Cha.png",
    "glow": "iscas_cores/isca-artificial-bubble-tube/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-bubble-tube/laranja-Neon.png",
    "pastel": "iscas_cores/isca-artificial-bubble-tube/Pastel.png",
    "pretobrilhante": "iscas_cores/isca-artificial-bubble-tube/preto-brilhante.png",
    "rapadura": "iscas_cores/isca-artificial-bubble-tube/Rapadura.png",
    "roxoestrelar": "iscas_cores/isca-artificial-bubble-tube/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-bubble-tube/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-bubble-tube/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-bubble-tube/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajitwin": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajitwin/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajitwin/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajitwin/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajitwin/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajitwin/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajitwin/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajitwin/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajitwin/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajitwin/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajitwin/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajitwin/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajitwin/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajitwin/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajineedle-1": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajineedle-1/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajineedle-1/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajineedle-1/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajineedle-1/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajineedle-1/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajineedle-1/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajineedle-1/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajineedle-1/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajineedle-1/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajineedle-1/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajineedle-1/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajineedle-1/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajineedle-1/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajiring": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajiring/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajiring/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajiring/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajiring/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajiring/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajiring/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajiring/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajiring/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajiring/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajiring/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajiring/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajiring/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajiring/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajishirimp": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajishirimp/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajishirimp/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajishirimp/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajishirimp/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajishirimp/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajishirimp/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajishirimp/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajishirimp/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajishirimp/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajishirimp/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajishirimp/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajishirimp/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajishirimp/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajisho": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajisho/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajisho/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajisho/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajisho/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajisho/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajisho/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajisho/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajisho/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajisho/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajisho/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajisho/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajisho/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajisho/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajistingv": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajistingv/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajistingv/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajistingv/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajistingv/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajistingv/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajistingv/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajistingv/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajistingv/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajistingv/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajistingv/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajistingv/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajistingv/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajistingv/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajimushi": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajimushi/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajimushi/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajimushi/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajimushi/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajimushi/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajimushi/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajimushi/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajimushi/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajimushi/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajimushi/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajimushi/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajimushi/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajimushi/Veu-da-noite.png"
  },
  "kit-isca-artificial-ajimizu": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajimizu/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajimizu/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajimizu/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajimizu/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajimizu/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajimizu/laranja-Neon.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajimizu/Pastel.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajimizu/preto-brilhante.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajimizu/Rapadura.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajimizu/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajimizu/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajimizu/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajimizu/Veu-da-noite.png"
  },
  "isca-artificial-shad-padoru": {
    "amareloneon": "iscas_cores/isca-artificial-shad-padoru/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-shad-padoru/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-shad-padoru/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-shad-padoru/Cha.png",
    "glow": "iscas_cores/isca-artificial-shad-padoru/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-shad-padoru/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/isca-artificial-shad-padoru/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/isca-artificial-shad-padoru/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-shad-padoru/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-shad-padoru/Vermelho-Holografico.png",
    "veudanoite": "iscas_cores/isca-artificial-shad-padoru/Veu-da-noite.png",
    "pastel": "iscas_cores/isca-artificial-shad-padoru/Pastel.png",
    "rapadura": "iscas_cores/isca-artificial-shad-padoru/Rapadura.png",
  },
  "isca-artificial-ajigrub": {
    "amareloneon": "iscas_cores/isca-artificial-ajigrub/amarelo-neon.png",
    "brancoperola": "iscas_cores/isca-artificial-ajigrub/Branco-perola.png",
    "capimrubi": "iscas_cores/isca-artificial-ajigrub/Capim-Rubi.png",
    "cha": "iscas_cores/isca-artificial-ajigrub/Cha.png",
    "glow": "iscas_cores/isca-artificial-ajigrub/Glow.png",
    "laranjaneon": "iscas_cores/isca-artificial-ajigrub/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/isca-artificial-ajigrub/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/isca-artificial-ajigrub/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/isca-artificial-ajigrub/Verde neon.png",
    "vermelhoholografico": "iscas_cores/isca-artificial-ajigrub/Vermelho-Holografico.png",
    "pastel": "iscas_cores/isca-artificial-ajigrub/Pastel.png",
    "rapadura": "iscas_cores/isca-artificial-ajigrub/Rapadura.png",
    "veudanoite": "iscas_cores/isca-artificial-ajigrub/Veu-da-noite.png",
  },
  "kit-isca-artificial-aji-fukura": {
    "amareloneon": "iscas_cores/kit-isca-artificial-aji-fukura/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-aji-fukura/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-aji-fukura/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-aji-fukura/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-aji-fukura/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-aji-fukura/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-aji-fukura/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-aji-fukura/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-aji-fukura/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-aji-fukura/Vermelho-Holografico.png",
    "pastel": "iscas_cores/kit-isca-artificial-aji-fukura/Pastel.png",
    "rapadura": "iscas_cores/kit-isca-artificial-aji-fukura/Rapadura.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-aji-fukura/Veu-da-noite.png",
  },
  "kit-isca-artificial-ajiaero": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajiaero/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajiaero/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajiaero/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajiaero/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajiaero/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajiaero/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajiaero/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajiaero/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajiaero/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajiaero/Vermelho-Holografico.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajiaero/Pastel.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajiaero/Rapadura.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajiaero/Veu-da-noite.png",
  },
  "kit-isca-artificial-ajibeast": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajibeast/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajibeast/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajibeast/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajibeast/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajibeast/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajibeast/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajibeast/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajibeast/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajibeast/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajibeast/Vermelho-Holografico.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajibeast/Pastel.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajibeast/Rapadura.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajibeast/Veu-da-noite.png",
  },
  "kit-isca-artificial-ajiegg": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajiegg/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajiegg/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajiegg/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajiegg/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajiegg/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajiegg/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajiegg/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajiegg/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajiegg/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajiegg/Vermelho-Holografico.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajiegg/Pastel.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajiegg/Rapadura.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajiegg/Veu-da-noite.png",
  },
  "kit-isca-artificial-ajihane": {
    "amareloneon2": "iscas_cores/kit-isca-artificial-ajihane/amarelo-neon-2.png",
    "amareloneon": "iscas_cores/kit-isca-artificial-ajihane/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajihane/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajihane/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajihane/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajihane/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajihane/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajihane/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajihane/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajihane/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajihane/Vermelho-Holografico.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajihane/Pastel.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajihane/Rapadura.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajihane/Veu-da-noite.png",
  },
  "kit-isca-artificial-ajikaze": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajikaze/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajikaze/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajikaze/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajikaze/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajikaze/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajikaze/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajikaze/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajikaze/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajikaze/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajikaze/Vermelho-Holografico.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajikaze/Pastel.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajikaze/Rapadura.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajikaze/Veu-da-noite.png",
  },
  "kit-isca-artificial-ajikoka": {
    "amareloneon": "iscas_cores/kit-isca-artificial-ajikoka/amarelo-neon.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-ajikoka/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-ajikoka/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-ajikoka/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-ajikoka/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-ajikoka/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-ajikoka/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-ajikoka/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-ajikoka/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-ajikoka/Vermelho-Holografico.png",
    "pastel": "iscas_cores/kit-isca-artificial-ajikoka/Pastel.png",
    "rapadura": "iscas_cores/kit-isca-artificial-ajikoka/Rapadura.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-ajikoka/Veu-da-noite.png",
  },
  "kit-isca-artificial-wave-grub": {
    "amareloneon": "iscas_cores/kit-isca-artificial-wave-grub/amarelo-neon.png",
    "brancoperola2": "iscas_cores/kit-isca-artificial-wave-grub/Branco-perola-2.png",
    "brancoperola": "iscas_cores/kit-isca-artificial-wave-grub/Branco-perola.png",
    "capimrubi": "iscas_cores/kit-isca-artificial-wave-grub/Capim-Rubi.png",
    "cha": "iscas_cores/kit-isca-artificial-wave-grub/Cha.png",
    "glow": "iscas_cores/kit-isca-artificial-wave-grub/Glow.png",
    "laranjaneon": "iscas_cores/kit-isca-artificial-wave-grub/laranja-Neon.png",
    "pretobrilhante": "iscas_cores/kit-isca-artificial-wave-grub/preto-brilhante.png",
    "roxoestrelar": "iscas_cores/kit-isca-artificial-wave-grub/Roxo-Estrelnar.png",
    "verdeneon": "iscas_cores/kit-isca-artificial-wave-grub/Verde neon.png",
    "vermelhoholografico": "iscas_cores/kit-isca-artificial-wave-grub/Vermelho-Holografico.png",
    "pastel": "iscas_cores/kit-isca-artificial-wave-grub/Pastel.png",
    "rapadura": "iscas_cores/kit-isca-artificial-wave-grub/Rapadura.png",
    "veudanoite": "iscas_cores/kit-isca-artificial-wave-grub/Veu-da-noite.png",
  }
};

export const getLureColorImage = (handle, colorName) => {
  if (!handle || !colorName || !lureColorManifest[handle]) return null;
  
  const normColor = colorName.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/g, '');
    
  const handleMap = lureColorManifest[handle];
  
  // Exact match
  if (handleMap[normColor]) {
    return `${import.meta.env.BASE_URL}${handleMap[normColor]}`;
  }
  
  // Partial / Fuzzy match
  for (const [key, path] of Object.entries(handleMap)) {
    if (key.includes(normColor) || normColor.includes(key)) {
      return `${import.meta.env.BASE_URL}${path}`;
    }
  }
  
  return null;
};

// Hash simples e estavel de uma string (mesmo produto sempre cai na mesma cor)
const hashString = (str) => {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash);
};

// Escolhe uma foto de capa variada (mas estavel) entre as cores disponiveis do produto,
// usada no card do catalogo e no destaque da home para nao repetir sempre a mesma cor.
export const getVariedCoverImage = (product) => {
  if (!product || !product.id || !lureColorManifest[product.id]) return null;
  const manifestEntry = lureColorManifest[product.id];
  const colors = (product.options && product.options['Cor']) || [];
  if (colors.length > 0) {
    const index = hashString(product.id) % colors.length;
    const img = getLureColorImage(product.id, colors[index]);
    if (img) return img;
  }
  const firstPath = Object.values(manifestEntry)[0];
  return firstPath ? `${import.meta.env.BASE_URL}${firstPath}` : null;
};
